// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wire

import (
	"context"
	"time"

	"github.com/pscheid92/voiceline-diary/internal/diary"
	mock "github.com/stretchr/testify/mock"
)

// newMockDiary creates a new instance of mockDiary. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDiary(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDiary {
	mock := &mockDiary{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDiary is an autogenerated mock type for the Diary type
type mockDiary struct {
	mock.Mock
}

type mockDiary_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDiary) EXPECT() *mockDiary_Expecter {
	return &mockDiary_Expecter{mock: &_m.Mock}
}

// File provides a mock function for the type mockDiary
func (_mock *mockDiary) File(ctx context.Context, entry diary.Entry, now time.Time) (string, error) {
	ret := _mock.Called(ctx, entry, now)

	if len(ret) == 0 {
		panic("no return value specified for File")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, diary.Entry, time.Time) (string, error)); ok {
		return returnFunc(ctx, entry, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, diary.Entry, time.Time) string); ok {
		r0 = returnFunc(ctx, entry, now)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, diary.Entry, time.Time) error); ok {
		r1 = returnFunc(ctx, entry, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDiary_File_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'File'
type mockDiary_File_Call struct {
	*mock.Call
}

// File is a helper method to define mock.On call
//   - ctx context.Context
//   - entry diary.Entry
//   - now time.Time
func (_e *mockDiary_Expecter) File(ctx any, entry any, now any) *mockDiary_File_Call {
	return &mockDiary_File_Call{Call: _e.mock.On("File", ctx, entry, now)}
}

func (_c *mockDiary_File_Call) Run(run func(ctx context.Context, entry diary.Entry, now time.Time)) *mockDiary_File_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 diary.Entry
		if args[1] != nil {
			arg1 = args[1].(diary.Entry)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDiary_File_Call) Return(s string, err error) *mockDiary_File_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockDiary_File_Call) RunAndReturn(run func(ctx context.Context, entry diary.Entry, now time.Time) (string, error)) *mockDiary_File_Call {
	_c.Call.Return(run)
	return _c
}
