// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wire

import (
	"context"

	"github.com/pscheid92/voiceline-diary/internal/conversation"
	mock "github.com/stretchr/testify/mock"
)

// newMockCompanion creates a new instance of mockCompanion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCompanion(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCompanion {
	mock := &mockCompanion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockCompanion is an autogenerated mock type for the Companion type
type mockCompanion struct {
	mock.Mock
}

type mockCompanion_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCompanion) EXPECT() *mockCompanion_Expecter {
	return &mockCompanion_Expecter{mock: &_m.Mock}
}

// Answer provides a mock function for the type mockCompanion
func (_mock *mockCompanion) Answer(ctx context.Context, call conversation.Call, refusal string) error {
	ret := _mock.Called(ctx, call, refusal)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, conversation.Call, string) error); ok {
		r0 = returnFunc(ctx, call, refusal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCompanion_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type mockCompanion_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - ctx context.Context
//   - call conversation.Call
//   - refusal string
func (_e *mockCompanion_Expecter) Answer(ctx any, call any, refusal any) *mockCompanion_Answer_Call {
	return &mockCompanion_Answer_Call{Call: _e.mock.On("Answer", ctx, call, refusal)}
}

func (_c *mockCompanion_Answer_Call) Run(run func(ctx context.Context, call conversation.Call, refusal string)) *mockCompanion_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 conversation.Call
		if args[1] != nil {
			arg1 = args[1].(conversation.Call)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockCompanion_Answer_Call) Return(err error) *mockCompanion_Answer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCompanion_Answer_Call) RunAndReturn(run func(ctx context.Context, call conversation.Call, refusal string) error) *mockCompanion_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// AskFor provides a mock function for the type mockCompanion
func (_mock *mockCompanion) AskFor(ctx context.Context, missing []string) error {
	ret := _mock.Called(ctx, missing)

	if len(ret) == 0 {
		panic("no return value specified for AskFor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, missing)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCompanion_AskFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskFor'
type mockCompanion_AskFor_Call struct {
	*mock.Call
}

// AskFor is a helper method to define mock.On call
//   - ctx context.Context
//   - missing []string
func (_e *mockCompanion_Expecter) AskFor(ctx any, missing any) *mockCompanion_AskFor_Call {
	return &mockCompanion_AskFor_Call{Call: _e.mock.On("AskFor", ctx, missing)}
}

func (_c *mockCompanion_AskFor_Call) Run(run func(ctx context.Context, missing []string)) *mockCompanion_AskFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCompanion_AskFor_Call) Return(err error) *mockCompanion_AskFor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCompanion_AskFor_Call) RunAndReturn(run func(ctx context.Context, missing []string) error) *mockCompanion_AskFor_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type mockCompanion
func (_mock *mockCompanion) Close() {
	_mock.Called()
	return
}

// mockCompanion_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockCompanion_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockCompanion_Expecter) Close() *mockCompanion_Close_Call {
	return &mockCompanion_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockCompanion_Close_Call) Run(run func()) *mockCompanion_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCompanion_Close_Call) Return() *mockCompanion_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockCompanion_Close_Call) RunAndReturn(run func()) *mockCompanion_Close_Call {
	_c.Run(run)
	return _c
}

// EndTurn provides a mock function for the type mockCompanion
func (_mock *mockCompanion) EndTurn(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EndTurn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCompanion_EndTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndTurn'
type mockCompanion_EndTurn_Call struct {
	*mock.Call
}

// EndTurn is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCompanion_Expecter) EndTurn(ctx any) *mockCompanion_EndTurn_Call {
	return &mockCompanion_EndTurn_Call{Call: _e.mock.On("EndTurn", ctx)}
}

func (_c *mockCompanion_EndTurn_Call) Run(run func(ctx context.Context)) *mockCompanion_EndTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockCompanion_EndTurn_Call) Return(err error) *mockCompanion_EndTurn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCompanion_EndTurn_Call) RunAndReturn(run func(ctx context.Context) error) *mockCompanion_EndTurn_Call {
	_c.Call.Return(run)
	return _c
}

// Greet provides a mock function for the type mockCompanion
func (_mock *mockCompanion) Greet(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Greet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCompanion_Greet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Greet'
type mockCompanion_Greet_Call struct {
	*mock.Call
}

// Greet is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCompanion_Expecter) Greet(ctx any) *mockCompanion_Greet_Call {
	return &mockCompanion_Greet_Call{Call: _e.mock.On("Greet", ctx)}
}

func (_c *mockCompanion_Greet_Call) Run(run func(ctx context.Context)) *mockCompanion_Greet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockCompanion_Greet_Call) Return(err error) *mockCompanion_Greet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCompanion_Greet_Call) RunAndReturn(run func(ctx context.Context) error) *mockCompanion_Greet_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type mockCompanion
func (_mock *mockCompanion) Receive(ctx context.Context) (conversation.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 conversation.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (conversation.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) conversation.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(conversation.Event)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockCompanion_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type mockCompanion_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCompanion_Expecter) Receive(ctx any) *mockCompanion_Receive_Call {
	return &mockCompanion_Receive_Call{Call: _e.mock.On("Receive", ctx)}
}

func (_c *mockCompanion_Receive_Call) Run(run func(ctx context.Context)) *mockCompanion_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockCompanion_Receive_Call) Return(event conversation.Event, err error) *mockCompanion_Receive_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *mockCompanion_Receive_Call) RunAndReturn(run func(ctx context.Context) (conversation.Event, error)) *mockCompanion_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// SendAudio provides a mock function for the type mockCompanion
func (_mock *mockCompanion) SendAudio(ctx context.Context, pcm []byte) error {
	ret := _mock.Called(ctx, pcm)

	if len(ret) == 0 {
		panic("no return value specified for SendAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, pcm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCompanion_SendAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAudio'
type mockCompanion_SendAudio_Call struct {
	*mock.Call
}

// SendAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - pcm []byte
func (_e *mockCompanion_Expecter) SendAudio(ctx any, pcm any) *mockCompanion_SendAudio_Call {
	return &mockCompanion_SendAudio_Call{Call: _e.mock.On("SendAudio", ctx, pcm)}
}

func (_c *mockCompanion_SendAudio_Call) Run(run func(ctx context.Context, pcm []byte)) *mockCompanion_SendAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCompanion_SendAudio_Call) Return(err error) *mockCompanion_SendAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCompanion_SendAudio_Call) RunAndReturn(run func(ctx context.Context, pcm []byte) error) *mockCompanion_SendAudio_Call {
	_c.Call.Return(run)
	return _c
}
