// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package session

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockUser creates a new instance of mockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUser {
	mock := &mockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockUser is an autogenerated mock type for the User type
type mockUser struct {
	mock.Mock
}

type mockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUser) EXPECT() *mockUser_Expecter {
	return &mockUser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockUser
func (_mock *mockUser) Close(reason string) {
	_mock.Called(reason)
	return
}

// mockUser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockUser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - reason string
func (_e *mockUser_Expecter) Close(reason any) *mockUser_Close_Call {
	return &mockUser_Close_Call{Call: _e.mock.On("Close", reason)}
}

func (_c *mockUser_Close_Call) Run(run func(reason string)) *mockUser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockUser_Close_Call) Return() *mockUser_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockUser_Close_Call) RunAndReturn(run func(reason string)) *mockUser_Close_Call {
	_c.Run(run)
	return _c
}

// Emit provides a mock function for the type mockUser
func (_mock *mockUser) Emit(ctx context.Context, ev Event) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Event) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockUser_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type mockUser_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - ev Event
func (_e *mockUser_Expecter) Emit(ctx any, ev any) *mockUser_Emit_Call {
	return &mockUser_Emit_Call{Call: _e.mock.On("Emit", ctx, ev)}
}

func (_c *mockUser_Emit_Call) Run(run func(ctx context.Context, ev Event)) *mockUser_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Event
		if args[1] != nil {
			arg1 = args[1].(Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUser_Emit_Call) Return(err error) *mockUser_Emit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockUser_Emit_Call) RunAndReturn(run func(ctx context.Context, ev Event) error) *mockUser_Emit_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type mockUser
func (_mock *mockUser) Flush(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// mockUser_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type mockUser_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockUser_Expecter) Flush(ctx any) *mockUser_Flush_Call {
	return &mockUser_Flush_Call{Call: _e.mock.On("Flush", ctx)}
}

func (_c *mockUser_Flush_Call) Run(run func(ctx context.Context)) *mockUser_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockUser_Flush_Call) Return() *mockUser_Flush_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockUser_Flush_Call) RunAndReturn(run func(ctx context.Context)) *mockUser_Flush_Call {
	_c.Run(run)
	return _c
}

// Play provides a mock function for the type mockUser
func (_mock *mockUser) Play(ctx context.Context, pcm []byte) {
	_mock.Called(ctx, pcm)
	return
}

// mockUser_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type mockUser_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - ctx context.Context
//   - pcm []byte
func (_e *mockUser_Expecter) Play(ctx any, pcm any) *mockUser_Play_Call {
	return &mockUser_Play_Call{Call: _e.mock.On("Play", ctx, pcm)}
}

func (_c *mockUser_Play_Call) Run(run func(ctx context.Context, pcm []byte)) *mockUser_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockUser_Play_Call) Return() *mockUser_Play_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockUser_Play_Call) RunAndReturn(run func(ctx context.Context, pcm []byte)) *mockUser_Play_Call {
	_c.Run(run)
	return _c
}

// Read provides a mock function for the type mockUser
func (_mock *mockUser) Read(ctx context.Context) (Command, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 Command
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Command, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Command); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(Command)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUser_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockUser_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockUser_Expecter) Read(ctx any) *mockUser_Read_Call {
	return &mockUser_Read_Call{Call: _e.mock.On("Read", ctx)}
}

func (_c *mockUser_Read_Call) Run(run func(ctx context.Context)) *mockUser_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockUser_Read_Call) Return(command Command, err error) *mockUser_Read_Call {
	_c.Call.Return(command, err)
	return _c
}

func (_c *mockUser_Read_Call) RunAndReturn(run func(ctx context.Context) (Command, error)) *mockUser_Read_Call {
	_c.Call.Return(run)
	return _c
}
