// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gemini

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/genai"
)

// newMockConnection creates a new instance of mockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConnection {
	mock := &mockConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockConnection is an autogenerated mock type for the connection type
type mockConnection struct {
	mock.Mock
}

type mockConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConnection) EXPECT() *mockConnection_Expecter {
	return &mockConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockConnection
func (_mock *mockConnection) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockConnection_Expecter) Close() *mockConnection_Close_Call {
	return &mockConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockConnection_Close_Call) Run(run func()) *mockConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnection_Close_Call) Return(err error) *mockConnection_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnection_Close_Call) RunAndReturn(run func() error) *mockConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type mockConnection
func (_mock *mockConnection) Receive() (*genai.LiveServerMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 *genai.LiveServerMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*genai.LiveServerMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *genai.LiveServerMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*genai.LiveServerMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnection_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type mockConnection_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
func (_e *mockConnection_Expecter) Receive() *mockConnection_Receive_Call {
	return &mockConnection_Receive_Call{Call: _e.mock.On("Receive")}
}

func (_c *mockConnection_Receive_Call) Run(run func()) *mockConnection_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnection_Receive_Call) Return(liveServerMessage *genai.LiveServerMessage, err error) *mockConnection_Receive_Call {
	_c.Call.Return(liveServerMessage, err)
	return _c
}

func (_c *mockConnection_Receive_Call) RunAndReturn(run func() (*genai.LiveServerMessage, error)) *mockConnection_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// SendRealtimeInput provides a mock function for the type mockConnection
func (_mock *mockConnection) SendRealtimeInput(input genai.LiveRealtimeInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for SendRealtimeInput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(genai.LiveRealtimeInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnection_SendRealtimeInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRealtimeInput'
type mockConnection_SendRealtimeInput_Call struct {
	*mock.Call
}

// SendRealtimeInput is a helper method to define mock.On call
//   - input genai.LiveRealtimeInput
func (_e *mockConnection_Expecter) SendRealtimeInput(input any) *mockConnection_SendRealtimeInput_Call {
	return &mockConnection_SendRealtimeInput_Call{Call: _e.mock.On("SendRealtimeInput", input)}
}

func (_c *mockConnection_SendRealtimeInput_Call) Run(run func(input genai.LiveRealtimeInput)) *mockConnection_SendRealtimeInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 genai.LiveRealtimeInput
		if args[0] != nil {
			arg0 = args[0].(genai.LiveRealtimeInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnection_SendRealtimeInput_Call) Return(err error) *mockConnection_SendRealtimeInput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnection_SendRealtimeInput_Call) RunAndReturn(run func(input genai.LiveRealtimeInput) error) *mockConnection_SendRealtimeInput_Call {
	_c.Call.Return(run)
	return _c
}

// SendToolResponse provides a mock function for the type mockConnection
func (_mock *mockConnection) SendToolResponse(input genai.LiveToolResponseInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for SendToolResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(genai.LiveToolResponseInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnection_SendToolResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToolResponse'
type mockConnection_SendToolResponse_Call struct {
	*mock.Call
}

// SendToolResponse is a helper method to define mock.On call
//   - input genai.LiveToolResponseInput
func (_e *mockConnection_Expecter) SendToolResponse(input any) *mockConnection_SendToolResponse_Call {
	return &mockConnection_SendToolResponse_Call{Call: _e.mock.On("SendToolResponse", input)}
}

func (_c *mockConnection_SendToolResponse_Call) Run(run func(input genai.LiveToolResponseInput)) *mockConnection_SendToolResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 genai.LiveToolResponseInput
		if args[0] != nil {
			arg0 = args[0].(genai.LiveToolResponseInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnection_SendToolResponse_Call) Return(err error) *mockConnection_SendToolResponse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnection_SendToolResponse_Call) RunAndReturn(run func(input genai.LiveToolResponseInput) error) *mockConnection_SendToolResponse_Call {
	_c.Call.Return(run)
	return _c
}
