export const today = () =>
  new Date().toLocaleDateString(undefined, {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
  })

export const COPY = {
  wordmark: 'voiceline diary',
  ask: 'How was your day?',
  lede: 'Just start talking. The companion asks along the way, and you see the entry before anything is saved.',
  start: 'Start today’s entry',
  connecting: 'Connecting…',
  listening: 'Listening',
  speaking: 'Companion is speaking',
  saving: 'One moment…',
  done: 'Done speaking',
  finish: 'Finish conversation',
  abort: 'Leave without saving',
  save: 'Save to Notion',
  discard: 'Discard',
  again: 'Start another entry',
  open: 'Open in Notion',
  diary: 'Open your diary in Notion',
  review: 'Nothing is saved yet.',
  saved: 'Saved to your diary.',
  you: 'You',
  companion: 'Companion',
  retry: 'Try again',
  noRating: 'No rating — you didn’t give one, so none was invented.',
  mostly: 'Mostly',
  well: 'What went well',
  badly: 'What went badly',
  todos: 'On your mind for tomorrow',
  transcript: 'Read the conversation',
  previewTitle: 'Entry so far',
  previewRating: 'Rating',
  previewEmotion: 'Mood',
  previewGap: 'still open',
  upToThree: 'up to three',
  offer: 'The entry is complete — you can finish whenever you like.',
  clipping: 'Input is clipping — lower your microphone gain, the audio is distorted.',
  micDenied: 'Microphone access was denied.',
  micNeeded: 'Your browser will ask for the microphone.',
  pause: 'Pause',
  resume: 'Resume',
  paused: 'Paused — the companion cannot hear you',
  quiet: 'Nothing reaching the microphone',
  hearingYou: 'The microphone is picking you up',
  connectionLost: 'Connection lost.',
  connectionFailed: 'Connection failed.',
  lostReview:
    'Connection lost — this entry can no longer be saved. Copy anything you want to keep.',
  salvagedNote: 'The conversation ended early — this is what was captured.',
  stillAsking:
    'The entry still needs an answer — the question is coming. If you would rather not, you can leave without saving.',
  incompleteNote:
    'Aborted: an entry needs a rating and a mood. You can read it back here; nothing will be saved.',
  errors: {
    incomplete: 'Without a rating and a mood the entry is incomplete and will not be saved.',
    dial_failed: 'Could not start the conversation — please try again.',
    nothing_said: 'The conversation ended before anything was said — please start again.',
    read_failed: 'The entry came back in a shape we could not use — nothing was saved.',
    save_failed: 'Could not save the entry — please try again.',
    generic: 'Something went wrong — please try again.',
  },
}
